### ISSUE TITLE
Consider add Wireshark 2.x support?

### ISSUE THREAD

**Issue by DangZRQ** [jkcko/ieee802.15.4-tap#3]
I found that your change ([32141](https://code.wireshark.org/review/#/c/32141/) and [32262](https://code.wireshark.org/review/#/c/32262/)) are only merged to wireshark master 3.0, so I can not use your IEEE_802_15_4_TAP on wireshark 2.4/2.6 with [nRF-Sniffer-for-802.15.4](nRF-Sniffer-for-802.15.4). Could you please add wireshark 2.x support by submit PR to wireshark/master2.6 or 2.4?

**Comment by jkcko** [comment]
This feature request should be opened on Wireshark's bugzilla.  However, I'm pretty sure the Wireshark community are not accepting any new features on Wireshark 2.x even if I or anyone else backports it.  I barely got the changes accepted into 3.0.1 from master branch instead of having to wait until 3.1 for release integration only because there was enough interest and review was already ongoing. Wireshark has already moved on to 3.2 and is widely available.
